<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE VCALENDAR
[
<!ELEMENT VCALENDAR (CALSCALE, VERSION, PRODID, X-WR-CALNAME, METHOD, X-PUBLISHED-TTL, VEVENT) >
<!ELEMENT CALSCALE (#PCDATA)  >
<!ELEMENT VERSION (#PCDATA) >
<!ELEMENT PRODID (#PCDATA) >
<!ELEMENT X-WR-CALNAME (#PCDATA) >
<!ELEMENT METHOD (#PCDATA) >
<!ELEMENT X-PUBLISHED-TTL (#PCDATA) >
<!ELEMENT VEVENT (DTSTAMP, UID, SUMMARY, STATUS, DTSTART, DTEND, DESCRIPTION, ORGANIZER, LOCATION, CATEGORIES, URL) >
<!ELEMENT DTSTAMP (#PCDATA) >
<!ELEMENT UID (#PCDATA) >
<!ELEMENT SUMMARY (#PCDATA) >
<!ELEMENT STATUS (#PCDATA) >
<!ELEMENT DTSTART (#PCDATA) >
<!ELEMENT DTEND (#PCDATA) >
<!ELEMENT DESCRIPTION (#PCDATA) >
<!ELEMENT ORGANIZER (#PCDATA) >
<!ELEMENT LOCATION (#PCDATA) >
<!ELEMENT CATEGORIES (#PCDATA) >
<!ELEMENT URL (#PCDATA) >
]>

<VCALENDAR>
	<CALSCALE>GREGORIAN</CALSCALE>
	<VERSION>2.0</VERSION>
	<PRODID>-//Microsoft Corporation//Outlook 12.0 MIMEDIR//EN</PRODID>
	<X-WR-CALNAME>VALUE=TEXT:Cours Emse</X-WR-CALNAME> 
	<METHOD>PUBLISH</METHOD>
	<X-PUBLISHED-TTL>PT120M</X-PUBLISHED-TTL>
	<VEVENT>
		<DTSTAMP>20160114T081500Z</DTSTAMP>
		<UID>action94667-1</UID>
		<SUMMARY>Informatique / Security Trust Privacy</SUMMARY>
		<STATUS>CONFIRMED</STATUS>
		<DTSTART>20160114T061500Z</DTSTART>
		<DTEND>20160114T093000Z</DTEND>
		<DESCRIPTION>Intervenant :  -</DESCRIPTION>  
		<ORGANIZER>;VALUE=TEXT:</ORGANIZER>
		<LOCATION>A1.04[Amphis]</LOCATION>
		<CATEGORIES>Cours 2A + 3A</CATEGORIES>
		<URL>https://portailmetier.emse.fr/ApplisWeb/grr_ens/view_entry.php?id=94667</URL>
	</VEVENT>
</VCALENDAR>
