<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?> <!DOCTYPE chequier [ <!ELEMENT chequier (cheque*)> <!ELEMENT recipiendaire (nom)> <!ELEMENT emetteur (nom)> <!ELEMENT montant (#PCDATA)> <!ELEMENT cheque (recipiendaire,emetteur,montant)> <!ELEMENT nom (#PCDATA)> <!ATTLIST cheque commentaire CDATA #IMPLIED numero ID #REQUIRED > <!ATTLIST recipiendaire commentaire CDATA #IMPLIED> <!ATTLIST emetteur commentaire CDATA #IMPLIED> ]> <chequier> <cheque commentaire="loyer" numero="cheque1324"> <recipiendaire commentaire="mon ami"> <nom>Jean</nom> </recipiendaire> <emetteur> <nom>Martin</nom> </emetteur> <montant>10$</montant> </cheque> <cheque commentaire="encore le loyer" numero="cheque1324"> <recipiendaire commentaire="mon ami (encore)"> <nom>Jean</nom> </recipiendaire> <emetteur> <nom>Martin</nom> </emetteur> <montant>10$</montant> </cheque> </chequier>
